import eslint from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  {
    ignores: [
      // Dependencies
      "node_modules/**",

      // Build outputs
      "dist/**",
      "**/dist/**",

      // Generated code (Prisma, TypeGraphQL, codegen pipeline)
      "src/generated/**",

      // Auto-generated model CRUD files (PascalCase files in src/ root)
      // These are generated by npm run generate:functions and contain
      // TypeGraphQL/Prisma patterns with unavoidable `any` types
      "src/[A-Z]*.ts",

      // Module codegen scripts
      "src/modules/**",

      // Declaration files
      "**/*.d.ts",

      // Build/config files
      "*.config.js",
      "*.config.cjs",
      "*.config.mjs",
      "*.config.ts",

      // Utility scripts
      "*.mjs",
      "*.cjs",
    ],
  },
  {
    files: ["src/**/*.ts"],
    ignores: [
      "src/generated/**",
      "src/modules/**",
      "**/__tests__/**",
      "**/*.test.ts",
      "**/*.spec.ts",
    ],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        project: "./tsconfig.json",
      },
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        NodeJS: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...eslint.configs.recommended.rules,
      ...tseslint.configs["recommended"].rules,

      // TypeScript strict checking - warn initially given generated code
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],

      // Floating promises must be handled
      "@typescript-eslint/no-floating-promises": "error",

      // No eslint-disable comments (enforced via no-restricted-syntax)
      "no-restricted-syntax": [
        "error",
        {
          selector: "Program > :first-child[type='Line']",
          message: "eslint-disable comments are not allowed.",
        },
      ],

      // Code quality
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-var": "error",
      "prefer-const": "warn",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-undef": "off", // TypeScript handles this
      "no-case-declarations": "warn",
      "no-throw-literal": "warn",

      // Allow require() for legacy codegen scripts
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  {
    // Test files - relaxed rules
    files: [
      "**/__tests__/**/*.ts",
      "**/*.test.ts",
      "**/*.spec.ts",
    ],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        NodeJS: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        test: "readonly",
        vi: "readonly",
        fail: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...eslint.configs.recommended.rules,

      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],

      "no-console": "off",
      "no-debugger": "warn",
      "no-var": "error",
      "prefer-const": "warn",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-undef": "off",
      "no-unused-vars": "off",
      "no-case-declarations": "warn",
    },
  },
];
