-- Seed TradingPolicy records from existing AlpacaAccount data.
-- Every active AlpacaAccount gets a TradingPolicy with values derived from
-- existing account fields. Idempotent: skips accounts that already have a policy.

INSERT INTO "trading_policies" (
  "id",
  "alpacaAccountId",
  "version",
  "lastModifiedBy",
  "lastModifiedAt",
  "autonomyMode",
  "realtimeTradingEnabled",
  "paperTradingOnly",
  "killSwitchEnabled",
  "equitiesEnabled",
  "etfsEnabled",
  "cryptoEnabled",
  "optionsEnabled",
  "futuresEnabled",
  "forexEnabled",
  "shortingEnabled",
  "marginEnabled",
  "fractionalSharesEnabled",
  "maxBuyingPowerUtilPct",
  "cashFloorPct",
  "maxGrossExposurePct",
  "maxNetExposurePct",
  "maxLeverage",
  "maxSymbolConcentrationPct",
  "maxSectorConcentrationPct",
  "maxOpenPositions",
  "maxOpenOrders",
  "macroOverlayEnabled",
  "sectorOverlayEnabled",
  "volatilityOverlayEnabled",
  "liquidityStressOverlayEnabled",
  "blackSwanProtectionEnabled",
  "drawdownGuardianEnabled",
  "correlationSpikeProtectionEnabled",
  "newsEventRiskOverlayEnabled",
  "exchangeHealthOverlayEnabled",
  "dataQualitySentinelEnabled",
  "createdAt",
  "updatedAt"
)
SELECT
  gen_random_uuid(),
  aa."id",
  1,
  'system:migration',
  NOW(),
  'ADVISORY_ONLY'::"AutonomyMode",
  aa."realTime",
  CASE WHEN aa."type" = 'PAPER' THEN true ELSE false END,
  false,
  true,
  true,
  aa."cryptoTradingEnabled",
  false,
  false,
  false,
  false,
  false,
  true,
  90,
  10,
  100,
  100,
  1,
  15,
  30,
  20,
  50,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  NOW(),
  NOW()
FROM "alpaca_accounts" aa
WHERE aa."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "trading_policies" tp WHERE tp."alpacaAccountId" = aa."id"
  );
