/*
  Warnings:

  - The `signal` column on the `trades` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `strategy` column on the `trades` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "TradeStrategy" AS ENUM ('TECHNICAL_ANALYSIS', 'TREND_FOLLOWING', 'MEAN_REVERSION', 'OPTIONS_STRATEGY', 'MOMENTUM_STRATEGY', 'ARBITRAGE', 'STATISTICAL_ARBITRAGE', 'MARKET_MAKING', 'NEWS_BASED_STRATEGY', 'SENTIMENT_ANALYSIS', 'LIQUIDITY_PROVISION', 'SCALPING', 'VOLATILITY_TRADING', 'EVENT_DRIVEN', 'BREAKOUT_STRATEGY', 'ORDER_FLOW_TRADING', 'PAIR_TRADING', 'SECTOR_ROTATION', 'HIGH_FREQUENCY_TRADING', 'MACHINE_VISION_ANALYSIS');

-- CreateEnum
CREATE TYPE "TradeSignal" AS ENUM ('GOLDEN_CROSS', 'MOVING_AVERAGE_CROSSOVER', 'RSI_OVERBOUGHT', 'RSI_OVERSOLD', 'MACD_CROSSOVER', 'BOLLINGER_BANDS_BREAKOUT', 'TREND_REVERSAL', 'VOLATILITY_SPIKE', 'PRICE_ACTION', 'IMPLIED_VOLATILITY_SURGE', 'BREAKOUT_ABOVE_RESISTANCE', 'BREAKDOWN_BELOW_SUPPORT', 'SUPPORT_LEVEL_HOLD', 'RESISTANCE_LEVEL_HOLD', 'FIBONACCI_RETRACEMENT', 'ELLIOTT_WAVE', 'PARABOLIC_SAR', 'ADX_TREND_STRENGTH', 'CCI_OVERBOUGHT', 'CCI_OVERSOLD', 'STOCHASTIC_OVERSOLD', 'STOCHASTIC_OVERBOUGHT', 'DIVERGENCE_SIGNAL', 'GANN_FAN', 'DONCHIAN_CHANNEL_BREAKOUT', 'PIVOT_POINT', 'KELTNER_CHANNEL_BREAK', 'HEIKIN_ASHI_CROSSOVER', 'VOLUME_SURGE', 'ORDER_BOOK_IMBALANCE', 'TIME_SERIES_ANOMALY', 'MEAN_REVERSION_LEVEL', 'PAIR_TRADING_SIGNAL', 'SENTIMENT_SCORE_THRESHOLD', 'NEWS_SENTIMENT_CHANGE', 'ORDER_FLOW_IMPACT', 'LIQUIDITY_DRIVEN_MOVE', 'MACHINE_LEARNING_PREDICTION', 'SENTIMENT_ANALYSIS_TRIGGER');

-- AlterTable
ALTER TABLE "trades" DROP COLUMN "signal",
ADD COLUMN     "signal" "TradeSignal" NOT NULL DEFAULT 'PRICE_ACTION',
DROP COLUMN "strategy",
ADD COLUMN     "strategy" "TradeStrategy" NOT NULL DEFAULT 'TECHNICAL_ANALYSIS';
