-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "type" SET DEFAULT 'MARKET',
ALTER COLUMN "status" SET DEFAULT 'NEW',
ALTER COLUMN "side" SET DEFAULT 'BUY',
ALTER COLUMN "timeInForce" SET DEFAULT 'GTC';
