/*
  Warnings:

  - The values [VOLATILITY_SPIKE,ELLIOTT_WAVE,PARABOLIC_SAR,ADX_TREND_STRENGTH,CCI_OVERBOUGHT,CCI_OVERSOLD,DIVERGENCE_SIGNAL,GANN_FAN,DONCHIAN_CHANNEL_BREAKOUT,KELTNER_CHANNEL_BREAK,HEIKIN_ASHI_CROSSOVER,ORDER_BOOK_IMBALANCE,TIME_SERIES_ANOMALY,PAIR_TRADING_SIGNAL,SENTIMENT_SCORE_THRESHOLD,ORDER_FLOW_IMPACT,LIQUIDITY_DRIVEN_MOVE,MACHINE_LEARNING_PREDICTION] on the enum `TradeSignal` will be removed. If these variants are still used in the database, this will fail.
  - The values [OPTIONS_STRATEGY,MARKET_MAKING,SENTIMENT_ANALYSIS] on the enum `TradeStrategy` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TradeSignal_new" AS ENUM ('GOLDEN_CROSS', 'DEATH_CROSS', 'MOVING_AVERAGE_CROSSOVER', 'RSI_OVERBOUGHT', 'RSI_OVERSOLD', 'MACD_CROSSOVER', 'BOLLINGER_BANDS_BREAKOUT', 'TREND_REVERSAL', 'PRICE_ACTION', 'IMPLIED_VOLATILITY_SURGE', 'BREAKOUT_ABOVE_RESISTANCE', 'BREAKDOWN_BELOW_SUPPORT', 'SUPPORT_LEVEL_HOLD', 'RESISTANCE_LEVEL_HOLD', 'FIBONACCI_RETRACEMENT', 'STOCHASTIC_OVERSOLD', 'STOCHASTIC_OVERBOUGHT', 'PIVOT_POINT', 'VOLUME_SURGE', 'MEAN_REVERSION_LEVEL', 'NEWS_SENTIMENT_CHANGE', 'SENTIMENT_ANALYSIS_TRIGGER', 'GAP_AND_GO_LONG', 'GAP_AND_GO_SHORT', 'GAP_FADE_LONG', 'GAP_FADE_SHORT', 'ORB_BREAKOUT', 'ORB_BREAKDOWN', 'VWAP_BOUNCE', 'VWAP_REJECTION', 'NO_EARLY_SIGNAL', 'NO_SIGNAL');
ALTER TABLE "trades" ALTER COLUMN "signal" DROP DEFAULT;
ALTER TABLE "trades" ALTER COLUMN "signal" TYPE "TradeSignal_new" USING ("signal"::text::"TradeSignal_new");
ALTER TYPE "TradeSignal" RENAME TO "TradeSignal_old";
ALTER TYPE "TradeSignal_new" RENAME TO "TradeSignal";
DROP TYPE "TradeSignal_old";
ALTER TABLE "trades" ALTER COLUMN "signal" SET DEFAULT 'PRICE_ACTION';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "TradeStrategy_new" AS ENUM ('TECHNICAL_ANALYSIS', 'TREND_FOLLOWING', 'MEAN_REVERSION', 'MOMENTUM_STRATEGY', 'NEWS_BASED_STRATEGY', 'SCALPING', 'VOLATILITY_TRADING', 'EVENT_DRIVEN', 'BREAKOUT_STRATEGY', 'ORDER_FLOW_TRADING', 'NO_STRATEGY');
ALTER TABLE "trades" ALTER COLUMN "strategy" DROP DEFAULT;
ALTER TABLE "trades" ALTER COLUMN "strategy" TYPE "TradeStrategy_new" USING ("strategy"::text::"TradeStrategy_new");
ALTER TYPE "TradeStrategy" RENAME TO "TradeStrategy_old";
ALTER TYPE "TradeStrategy_new" RENAME TO "TradeStrategy";
DROP TYPE "TradeStrategy_old";
ALTER TABLE "trades" ALTER COLUMN "strategy" SET DEFAULT 'TECHNICAL_ANALYSIS';
COMMIT;
