// This file is auto-generated by modules/index.d.ts
// CRITICAL: Import reflect-metadata FIRST before any TypeGraphQL code
// This polyfill must be loaded before any decorators are evaluated
import "reflect-metadata";

export type * as types from './generated/typegraphql-prisma/models/index.d.ts';
export * as enums from './generated/typegraphql-prisma/enums/index';
export * from './generated/typeStrings/index';

// Export custom resolvers
export * from './resolvers/custom/index';

// Re-export Apollo Client functions from client.ts
export {
  getApolloClient,
  getApolloModules,
  configureConnectionPool,
  setTokenProvider,
  stopClient,
  getPoolStats,
  client
} from './client';

export type {
  ApolloClientType,
  InMemoryCacheType,
  HttpLinkType,
  NormalizedCacheObject,
  TokenProvider,
  PoolStats,
} from './client';


import { ABTest } from './ABTest';
import { Account } from './Account';
import { AccountDecisionRecord } from './AccountDecisionRecord';
import { AccountLinkingRequest } from './AccountLinkingRequest';
import { AccountRiskMetrics } from './AccountRiskMetrics';
import { Action } from './Action';
import { Alert } from './Alert';
import { Allocation } from './Allocation';
import { AlpacaAccount } from './AlpacaAccount';
import { AnalyticsConfiguration } from './AnalyticsConfiguration';
import { AnalyticsSnapshot } from './AnalyticsSnapshot';
import { Asset } from './Asset';
import { AuditLog } from './AuditLog';
import { Authenticator } from './Authenticator';
import { BrokerageAccount } from './BrokerageAccount';
import { Configuration } from './Configuration';
import { ConflictEvent } from './ConflictEvent';
import { ConnectionHealthSnapshot } from './ConnectionHealthSnapshot';
import { Customer } from './Customer';
import { DeadLetterMessage } from './DeadLetterMessage';
import { DecisionMemorySummary } from './DecisionMemorySummary';
import { EconomicEvent } from './EconomicEvent';
import { EquityBar } from './EquityBar';
import { Event } from './Event';
import { EventSnapshot } from './EventSnapshot';
import { FeatureImportanceAnalysis } from './FeatureImportanceAnalysis';
import { Fund } from './Fund';
import { FundAssignment } from './FundAssignment';
import { Holding } from './Holding';
import { InstitutionalFlowSignal } from './InstitutionalFlowSignal';
import { InstitutionalHolding } from './InstitutionalHolding';
import { InstitutionalSentimentAlerts } from './InstitutionalSentimentAlerts';
import { InstitutionalSentimentErrors } from './InstitutionalSentimentErrors';
import { InstitutionalSentimentHistory } from './InstitutionalSentimentHistory';
import { InstitutionalSentimentMetrics } from './InstitutionalSentimentMetrics';
import { Investor } from './Investor';
import { InvestorDocument } from './InvestorDocument';
import { InvestorTransaction } from './InvestorTransaction';
import { InviteToken } from './InviteToken';
import { LinkedProvider } from './LinkedProvider';
import { LlmConfiguration } from './LlmConfiguration';
import { MLModelVersion } from './MLModelVersion';
import { MLTrainingData } from './MLTrainingData';
import { MarketSentiment } from './MarketSentiment';
import { ModelArtifact } from './ModelArtifact';
import { ModelVersion } from './ModelVersion';
import { ModelVersionArtifact } from './ModelVersionArtifact';
import { NewsArticle } from './NewsArticle';
import { NewsArticleAssetSentiment } from './NewsArticleAssetSentiment';
import { NotificationDelivery } from './NotificationDelivery';
import { NotificationEvent } from './NotificationEvent';
import { NotificationPreference } from './NotificationPreference';
import { OptionsContract } from './OptionsContract';
import { OptionsGreeksHistory } from './OptionsGreeksHistory';
import { OptionsPosition } from './OptionsPosition';
import { OptionsPositionEvent } from './OptionsPositionEvent';
import { OptionsTradeExecution } from './OptionsTradeExecution';
import { OrgMembership } from './OrgMembership';
import { Organization } from './Organization';
import { PolicyOverlay } from './PolicyOverlay';
import { PortfolioGreeksHistory } from './PortfolioGreeksHistory';
import { RiskEscalationEvent } from './RiskEscalationEvent';
import { ScheduledOptionOrder } from './ScheduledOptionOrder';
import { Session } from './Session';
import { SignalGeneratorMetrics } from './SignalGeneratorMetrics';
import { SignalLineage } from './SignalLineage';
import { SignalOutcome } from './SignalOutcome';
import { SignalPriorityQueue } from './SignalPriorityQueue';
import { StrategyHealthSnapshot } from './StrategyHealthSnapshot';
import { SyncEvent } from './SyncEvent';
import { SystemAlert } from './SystemAlert';
import { TaxDocument } from './TaxDocument';
import { Trade } from './Trade';
import { TradeAuditEvent } from './TradeAuditEvent';
import { TradeExecutionHistory } from './TradeExecutionHistory';
import { TradeOutcome } from './TradeOutcome';
import { TradingPolicy } from './TradingPolicy';
import { User } from './User';
import { VerificationToken } from './VerificationToken';
import { WaitlistEntry } from './WaitlistEntry';

const adaptic = {
  aBTest: ABTest,
  account: Account,
  accountDecisionRecord: AccountDecisionRecord,
  accountLinkingRequest: AccountLinkingRequest,
  accountRiskMetrics: AccountRiskMetrics,
  action: Action,
  alert: Alert,
  allocation: Allocation,
  alpacaAccount: AlpacaAccount,
  analyticsConfiguration: AnalyticsConfiguration,
  analyticsSnapshot: AnalyticsSnapshot,
  asset: Asset,
  auditLog: AuditLog,
  authenticator: Authenticator,
  brokerageAccount: BrokerageAccount,
  configuration: Configuration,
  conflictEvent: ConflictEvent,
  connectionHealthSnapshot: ConnectionHealthSnapshot,
  customer: Customer,
  deadLetterMessage: DeadLetterMessage,
  decisionMemorySummary: DecisionMemorySummary,
  economicEvent: EconomicEvent,
  equityBar: EquityBar,
  event: Event,
  eventSnapshot: EventSnapshot,
  featureImportanceAnalysis: FeatureImportanceAnalysis,
  fund: Fund,
  fundAssignment: FundAssignment,
  holding: Holding,
  institutionalFlowSignal: InstitutionalFlowSignal,
  institutionalHolding: InstitutionalHolding,
  institutionalSentimentAlerts: InstitutionalSentimentAlerts,
  institutionalSentimentErrors: InstitutionalSentimentErrors,
  institutionalSentimentHistory: InstitutionalSentimentHistory,
  institutionalSentimentMetrics: InstitutionalSentimentMetrics,
  investor: Investor,
  investorDocument: InvestorDocument,
  investorTransaction: InvestorTransaction,
  inviteToken: InviteToken,
  linkedProvider: LinkedProvider,
  llmConfiguration: LlmConfiguration,
  mLModelVersion: MLModelVersion,
  mLTrainingData: MLTrainingData,
  marketSentiment: MarketSentiment,
  modelArtifact: ModelArtifact,
  modelVersion: ModelVersion,
  modelVersionArtifact: ModelVersionArtifact,
  newsArticle: NewsArticle,
  newsArticleAssetSentiment: NewsArticleAssetSentiment,
  notificationDelivery: NotificationDelivery,
  notificationEvent: NotificationEvent,
  notificationPreference: NotificationPreference,
  optionsContract: OptionsContract,
  optionsGreeksHistory: OptionsGreeksHistory,
  optionsPosition: OptionsPosition,
  optionsPositionEvent: OptionsPositionEvent,
  optionsTradeExecution: OptionsTradeExecution,
  orgMembership: OrgMembership,
  organization: Organization,
  policyOverlay: PolicyOverlay,
  portfolioGreeksHistory: PortfolioGreeksHistory,
  riskEscalationEvent: RiskEscalationEvent,
  scheduledOptionOrder: ScheduledOptionOrder,
  session: Session,
  signalGeneratorMetrics: SignalGeneratorMetrics,
  signalLineage: SignalLineage,
  signalOutcome: SignalOutcome,
  signalPriorityQueue: SignalPriorityQueue,
  strategyHealthSnapshot: StrategyHealthSnapshot,
  syncEvent: SyncEvent,
  systemAlert: SystemAlert,
  taxDocument: TaxDocument,
  trade: Trade,
  tradeAuditEvent: TradeAuditEvent,
  tradeExecutionHistory: TradeExecutionHistory,
  tradeOutcome: TradeOutcome,
  tradingPolicy: TradingPolicy,
  user: User,
  verificationToken: VerificationToken,
  waitlistEntry: WaitlistEntry,
};

export default adaptic;
