// This file is auto-generated by modules/index.d.ts
export type * as types from './generated/typegraphql-prisma/models/index.d.ts';
export type * as enums from './generated/typegraphql-prisma/enums/index.d.ts';

import { AIRecommendation } from './AIRecommendation';
import { Account } from './Account';
import { Alert } from './Alert';
import { Asset } from './Asset';
import { Authenticator } from './Authenticator';
import { City } from './City';
import { Country } from './Country';
import { Customer } from './Customer';
import { EconomicEvent } from './EconomicEvent';
import { EnvironmentVariable } from './EnvironmentVariable';
import { Holding } from './Holding';
import { Location } from './Location';
import { News } from './News';
import { Order } from './Order';
import { RiskAllocation } from './RiskAllocation';
import { Session } from './Session';
import { State } from './State';
import { Trade } from './Trade';
import { User } from './User';
import { VerificationToken } from './VerificationToken';
import { Workspace } from './Workspace';
import { WorkspaceUser } from './WorkspaceUser';

const adaptic = {
  aIRecommendation: AIRecommendation,
  account: Account,
  alert: Alert,
  asset: Asset,
  authenticator: Authenticator,
  city: City,
  country: Country,
  customer: Customer,
  economicEvent: EconomicEvent,
  environmentVariable: EnvironmentVariable,
  holding: Holding,
  location: Location,
  news: News,
  order: Order,
  riskAllocation: RiskAllocation,
  session: Session,
  state: State,
  trade: Trade,
  user: User,
  verificationToken: VerificationToken,
  workspace: Workspace,
  workspaceUser: WorkspaceUser,
};

export default adaptic;
