// This file is auto-generated by modules/index.d.ts
// CRITICAL: Import reflect-metadata FIRST before any TypeGraphQL code
// This polyfill must be loaded before any decorators are evaluated
import 'reflect-metadata';

export type * as types from './generated/typegraphql-prisma/models/index.d.ts';
export * as enums from './generated/typegraphql-prisma/enums/index';
export * from './generated/typeStrings/index';

// Export custom resolvers
export * from './resolvers/custom/index';

// Re-export Apollo Client functions from client.ts
export {
  getApolloClient,
  getApolloModules,
  configureConnectionPool,
  setTokenProvider,
  client,
} from './client';

export type {
  ApolloClientType,
  InMemoryCacheType,
  HttpLinkType,
  NormalizedCacheObject,
  TokenProvider,
} from './client';

// Canonical TradingPolicy / LlmConfiguration / PolicyOverlay JSON shapes
// and effective-policy / effective-llm-config / kms-envelope helpers.
// Per charter §2.2, §2.4 F4/F6 and sub-project 2 spec §4.2, §4.3, §4.4.
// Consumers in engine, utils, lumic-utils, and platform import from here.
export type { TradingPolicyJson } from './types/trading-policy';
export { DEFAULT_TRADING_POLICY } from './types/trading-policy';
export type {
  LlmConfigurationJson,
  LlmProvider,
} from './types/llm-configuration';
export { DEFAULT_LLM_CONFIGURATION } from './types/llm-configuration';
export type {
  PolicyOverlayEntry,
  OverlayType,
  OverlaySeverity,
  OverlayStatus,
} from './types/policy-overlay';
export {
  effectivePolicy,
  EffectivePolicyContextError,
  brokerageAccountWithPolicyContextSelectionSet,
} from './helpers/effective-policy';
export type { BrokerageAccountWithPolicyContext } from './helpers/effective-policy';
export { effectiveLlmConfig } from './helpers/effective-llm-config';
export type { EncryptedApiKey } from './helpers/kms-envelope';
export { encryptApiKey, decryptApiKey } from './helpers/kms-envelope';

import { ABTest } from './ABTest';
import { Account } from './Account';
import { AccountLinkingRequest } from './AccountLinkingRequest';
import { Action } from './Action';
import { Alert } from './Alert';
import { Allocation } from './Allocation';
import { AnalyticsConfiguration } from './AnalyticsConfiguration';
import { AnalyticsSnapshot } from './AnalyticsSnapshot';
import { Asset } from './Asset';
import { AuditLog } from './AuditLog';
import { Authenticator } from './Authenticator';
import { BrokerageAccount } from './BrokerageAccount';
import { Configuration } from './Configuration';
import { ConflictEvent } from './ConflictEvent';
import { ConnectionHealthSnapshot } from './ConnectionHealthSnapshot';
import { Customer } from './Customer';
import { DashboardLayout } from './DashboardLayout';
import { DeadLetterMessage } from './DeadLetterMessage';
import { EconomicEvent } from './EconomicEvent';
import { Event } from './Event';
import { EventSnapshot } from './EventSnapshot';
import { FeatureImportanceAnalysis } from './FeatureImportanceAnalysis';
import { Fund } from './Fund';
import { FundAssignment } from './FundAssignment';
import { InstitutionalFlowSignal } from './InstitutionalFlowSignal';
import { InstitutionalHolding } from './InstitutionalHolding';
import { InstitutionalSentimentAlerts } from './InstitutionalSentimentAlerts';
import { InstitutionalSentimentErrors } from './InstitutionalSentimentErrors';
import { InstitutionalSentimentHistory } from './InstitutionalSentimentHistory';
import { InstitutionalSentimentMetrics } from './InstitutionalSentimentMetrics';
import { Investment } from './Investment';
import { Investor } from './Investor';
import { InviteToken } from './InviteToken';
import { LinkedProvider } from './LinkedProvider';
import { MLTrainingData } from './MLTrainingData';
import { MarketSentiment } from './MarketSentiment';
import { ModelArtifact } from './ModelArtifact';
import { ModelVersion } from './ModelVersion';
import { ModelVersionArtifact } from './ModelVersionArtifact';
import { NewsArticle } from './NewsArticle';
import { NewsArticleAssetSentiment } from './NewsArticleAssetSentiment';
import { OptionsContract } from './OptionsContract';
import { OptionsGreeksHistory } from './OptionsGreeksHistory';
import { OptionsPosition } from './OptionsPosition';
import { OptionsTradeExecution } from './OptionsTradeExecution';
import { OrgMembership } from './OrgMembership';
import { Organization } from './Organization';
import { PortfolioGreeksHistory } from './PortfolioGreeksHistory';
import { ScheduledOptionOrder } from './ScheduledOptionOrder';
import { Session } from './Session';
import { SignalGeneratorMetrics } from './SignalGeneratorMetrics';
import { SignalLineage } from './SignalLineage';
import { SignalOutcome } from './SignalOutcome';
import { SignalPriorityQueue } from './SignalPriorityQueue';
import { SyncEvent } from './SyncEvent';
import { SystemAlert } from './SystemAlert';
import { Trade } from './Trade';
import { TradeAuditEvent } from './TradeAuditEvent';
import { TradeExecutionHistory } from './TradeExecutionHistory';
import { User } from './User';
import { VerificationToken } from './VerificationToken';
import { WaitlistEntry } from './WaitlistEntry';

const adaptic = {
  aBTest: ABTest,
  account: Account,
  accountLinkingRequest: AccountLinkingRequest,
  action: Action,
  alert: Alert,
  allocation: Allocation,
  analyticsConfiguration: AnalyticsConfiguration,
  analyticsSnapshot: AnalyticsSnapshot,
  asset: Asset,
  auditLog: AuditLog,
  authenticator: Authenticator,
  brokerageAccount: BrokerageAccount,
  configuration: Configuration,
  conflictEvent: ConflictEvent,
  connectionHealthSnapshot: ConnectionHealthSnapshot,
  customer: Customer,
  dashboardLayout: DashboardLayout,
  deadLetterMessage: DeadLetterMessage,
  economicEvent: EconomicEvent,
  event: Event,
  eventSnapshot: EventSnapshot,
  featureImportanceAnalysis: FeatureImportanceAnalysis,
  fund: Fund,
  fundAssignment: FundAssignment,
  institutionalFlowSignal: InstitutionalFlowSignal,
  institutionalHolding: InstitutionalHolding,
  institutionalSentimentAlerts: InstitutionalSentimentAlerts,
  institutionalSentimentErrors: InstitutionalSentimentErrors,
  institutionalSentimentHistory: InstitutionalSentimentHistory,
  institutionalSentimentMetrics: InstitutionalSentimentMetrics,
  investment: Investment,
  investor: Investor,
  inviteToken: InviteToken,
  linkedProvider: LinkedProvider,
  mLTrainingData: MLTrainingData,
  marketSentiment: MarketSentiment,
  modelArtifact: ModelArtifact,
  modelVersion: ModelVersion,
  modelVersionArtifact: ModelVersionArtifact,
  newsArticle: NewsArticle,
  newsArticleAssetSentiment: NewsArticleAssetSentiment,
  optionsContract: OptionsContract,
  optionsGreeksHistory: OptionsGreeksHistory,
  optionsPosition: OptionsPosition,
  optionsTradeExecution: OptionsTradeExecution,
  orgMembership: OrgMembership,
  organization: Organization,
  portfolioGreeksHistory: PortfolioGreeksHistory,
  scheduledOptionOrder: ScheduledOptionOrder,
  session: Session,
  signalGeneratorMetrics: SignalGeneratorMetrics,
  signalLineage: SignalLineage,
  signalOutcome: SignalOutcome,
  signalPriorityQueue: SignalPriorityQueue,
  syncEvent: SyncEvent,
  systemAlert: SystemAlert,
  trade: Trade,
  tradeAuditEvent: TradeAuditEvent,
  tradeExecutionHistory: TradeExecutionHistory,
  user: User,
  verificationToken: VerificationToken,
  waitlistEntry: WaitlistEntry,
};

export default adaptic;
